### ISSUE TITLE
Aggiungere spiegazione sulle sezioni

### ISSUE THREAD

**Issue by Polpetta** [R-and-LaTeX/CorsoDiLatex#29]
**Description**
Manca la spiegazione sui capitoli/sezioni/sotto sezioni/pagagrafi ecc ecc...

Da aggiungere nelle slide `2-TipiDiDocumento`

**Other issues**

**Comment by mzanella** [comment]
![image](https://user-images.githubusercontent.com/12596262/31115097-42f48ea0-a821-11e7-967a-e24a9fa1e58f.png)
