### ISSUE TITLE
ex9 - update example when biber is available

### ISSUE THREAD

**Issue by EmanueleC** [R-and-LaTeX/CorsoDiLatex#77]
**Description** Update exercise on bibliography when biber is available
See my commit [here](https://github.com/R-and-LaTeX/CorsoDiLatex/commit/ebac01db7ea3e9236b87b073e44529fa06192920)

**Other issues**

**Comment by Polpetta** [comment]
Biber è disponibile nelle macchine del Lab ora

**Comment by EmanueleC** [comment]
Chiudo
